services:
  app:
    build: .
    container_name: wonder_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wonder_assets
    ports:
      - "5000:5000"
    networks:
      - db_network

  db:
    image: postgres:15
    container_name: wonder_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wonder_assets
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  db_network:
    driver: bridge