"""Added creator id to Categories

Revision ID: b154193d22eb
Revises: 7bc293283d78
Create Date: 2025-04-15 15:27:12.288648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b154193d22eb'
down_revision: Union[str, None] = '7bc293283d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'creator_id')
    # ### end Alembic commands ###
