"""Add item_url column to items table

Revision ID: eabc03f9cc17
Revises: 4ab5b8e13b3a
Create Date: 2025-04-22 21:16:27.425028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabc03f9cc17'
down_revision: Union[str, None] = '4ab5b8e13b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_url', sa.String(), nullable=False))
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    op.add_column('types', sa.Column('icon_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'icon_url')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'category_id')
    op.drop_column('items', 'item_url')
    # ### end Alembic commands ###
